name: release-publish

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install elm
        uses: JorelAli/setup-elm@v2
        with:
          elm-version: 0.19.1

      - name: Install nodejs
        uses: actions/setup-node@v2

      - name: Install uglify
        run: npm install uglify-js

      - name: build artifacts
        run: |
          mkdir -p ./build
          cp -a ./assets/. ./build/
          elm make --optimize --output=./build/premain.js src/Main.elm
          ./node_modules/.bin/uglifyjs ./build/premain.js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe" | ./node_modules/.bin/uglifyjs --mangle --output ./build/main.js
          rm ./build/premain.js

      - name: Upload S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          AWS_S3_BUCKET: ${{ secrets. AWS_S3_BUCKET }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'build'
